source 'https://rubygems.org'

gem 'activerecord-import'
gem 'database_cleaner'
gem 'faker'
gem 'pg'
gem 'pry'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-reloader'

# gem 'sinatra-param', require: 'sinatra/param'
