source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'pg'
gem 'rake'
gem 'sinatra-activerecord'
gem 'sinatra-reloader'
gem 'faker'
gem  'pry'
# gem 'sinatra-param', require: 'sinatra/param'
