development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: activebilling
  password: 'password'
  database: json_dev_api_database

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  adapter: postgresql
  host: localhost
  port: 5432
  username: activebilling
  password: 'password'
  database: json_dev_api_database_test
