development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: activebilling
  password: 'password'
  database: json_dev_api_database

production:
  adapter: postgresql
  host: localhost
  port: 5432
  username: activebilling
  password: 'password'
  database: json_prod_api_database

test:
  adapter: postgresql
  host: localhost
  port: 5432
  username: activebilling
  password: 'password'
  database: json_dev_api_database_test
